### ISSUE TITLE
bug: 동일 이메일을 가진 계정이 존재 할 경우 토큰관리 이슈 발생

### ISSUE THREAD

**Issue by HyunsooZo** [7th-wanted-pre-onboarding-teamN/sns-feed#19]
### 버그 or 개선사항

- 요구사항 에는 `Account`는 유니크하다고 명시되어있지만, 
  email 에 대해서는 별다른 제한사항이 없음
- 현재는 토큰 `Claim`을 이메일로 관리하고 있으므로 이 경우 중복된 사용자의 토큰이 씌워져
   두 개 계정 중 한 계정은 정상적인 인증절차가 불가능해짐. 
- 예 : account1, account2 가 있고 같은 이메일을 사용한다고 가정하면 , 
         둘의 토큰 관리는 동일한 키(이메일)로 관리되는 현상 생김.
### 영향

- 한 고객이 하나의 이메일로 2개 이상의 계정 생성 시 토큰 관리에 차질 

### 재현 방법

- 동일한 이메일을 사용하는 2개의 계정을 생성하여 두 개 각각 로그인 테스트

### 해결/개선 방안

- 유니크한 키로 사용될 `Account`를 클레임에 넣고 `redis` 키로 사용
- `UserDetailsServiceImpl`의 `loadByUserName` 파라메터 값을 Account로 변경

**Comment by madst0614** [comment]
토큰 발행 단위를 이메일에서 계정 기준으로 바꾼건가요?

**Comment by HyunsooZo** [comment]
@madst0614 

기존 클레임 (이메일 + 사용자Id)에서 
개선 클레임 (이메일 + 사용자계정 + 사용자ID) 로 변경했습니다. 

`.getIdFromToken()`,`.getEmailFromToken()`,`.getAccountFromToken()`
기능 개발해주실때 그대로 사용하시면되고 

변경된부분은 내부적인 인증 절차 + 레디스에 리프레시 토큰 저장할때의 키 입니다.
- `TokenProvider` 의 `getAuthentication()` 로직, 
- `UserDetailsServiceImpl(spring security 관련 인터페이스)` 내 오버라이딩 된
   `loadUserByUserName()`메서드 내부 로직 수정, 
-  `User(커스텀 User말고 스프링제공 User)` 의`UserName`을 `Account`를 사용하여
    `TokenProvider` 의 `getAuthentication()`에서 내부적으로 토큰으로 사용자정보확인 시 
    `Account`를 참조하도록 수정했습니다!
-  `redis` 에 리프레시 토큰 저장 시 기존 키 `token: {email}` -> 수정후 키 `token: {account}` 로 관리됩니다. 

참고가 되었으면 좋겠습니다

**Comment by madst0614** [comment]
깔끔하게 해결하신 것 같습니다!
